version: 2
project_name: strawpoll

builds:
  - id: strawpoll
    main: ./cmd/strawpoll
    binary: strawpoll
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
    ldflags:
      - -s -w
      - -X github.com/dedene/strawpoll-cli/internal/cmd.version={{ .Tag }}
      - -X github.com/dedene/strawpoll-cli/internal/cmd.commit={{ .ShortCommit }}
      - -X github.com/dedene/strawpoll-cli/internal/cmd.date={{ .Date }}

  - id: strawpoll_darwin
    main: ./cmd/strawpoll
    binary: strawpoll
    env:
      - CGO_ENABLED=1
    targets:
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -s -w
      - -X github.com/dedene/strawpoll-cli/internal/cmd.version={{ .Tag }}
      - -X github.com/dedene/strawpoll-cli/internal/cmd.commit={{ .ShortCommit }}
      - -X github.com/dedene/strawpoll-cli/internal/cmd.date={{ .Date }}

archives:
  - ids:
      - strawpoll
      - strawpoll_darwin
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

brews:
  - repository:
      owner: dedene
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/dedene/strawpoll-cli
    description: CLI for StrawPoll - create and manage polls from the command line
    license: MIT
    install: |
      bin.install "strawpoll"
    test: |
      system "#{bin}/strawpoll", "--version"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
