version: 2
project_name: strawpoll

builds:
  - main: ./cmd/strawpoll
    binary: strawpoll
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/dedene/strawpoll-cli/internal/cmd.version={{ .Tag }}
      - -X github.com/dedene/strawpoll-cli/internal/cmd.commit={{ .ShortCommit }}
      - -X github.com/dedene/strawpoll-cli/internal/cmd.date={{ .Date }}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

brews:
  - repository:
      owner: dedene
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/dedene/strawpoll-cli
    description: CLI for StrawPoll - create and manage polls from the command line
    license: MIT
    install: |
      bin.install "strawpoll"
    test: |
      system "#{bin}/strawpoll", "--version"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
